# Generated by Django 2.2.28 on 2024-06-20 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_remove_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('club_president', 'Club President'), ('student', 'Student'), ('faculty', 'Faculty')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usercoin',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='usercoin',
            name='updated_user',
        ),
        migrations.RemoveField(
            model_name='usercoin',
            name='user',
        ),
        migrations.DeleteModel(
            name='EventUserWishList',
        ),
        migrations.DeleteModel(
            name='UserCoin',
        ),
    ]
