# Generated by Django 2.2.28 on 2024-06-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20240620_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='priority',
        ),
    ]
