# Generated by Django 2.2.28 on 2024-06-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20240620_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='job_category',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EventJobCategoryLinking',
        ),
    ]
