# Generated by Django 2.2.28 on 2024-06-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='status',
        ),
    ]
