# Generated by Django 2.2.28 on 2024-06-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_eventcategory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmember',
            name='attend_status',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='status',
        ),
    ]
