# Generated by Django 2.2.28 on 2024-06-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20240620_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='uid',
        ),
    ]
