# Generated by Django 2.2.28 on 2024-06-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventagenda',
            name='session_name',
        ),
    ]
