# Generated by Django 2.2.28 on 2024-06-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_eventagenda_session_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventagenda',
            name='venue_name',
        ),
    ]
